/* Generated by tools/update-card-catalogue.js. Edit catalogue/cards.json; helpers: tools/templates/cards-runtime.js. */
const CARD_CATALOGUE_REVISION = "2ba8f10ae1c55207a4847e8d164ae311b8281973f44daa7bb004174a428a4669";
const CARDS = [
  {
    "name": "スケルトン",
    "english": "Skeletons",
    "slug": "skeletons",
    "id": 26000010,
    "yomi": "スケルトン スケ",
    "cost": 1,
    "type": "troop",
    "role": "サイクル・防衛",
    "img": "https://cdn.royaleapi.com/static/img/cards/skeletons.png?v=c709c5b74fb9f981",
    "evolved": true,
    "imgEvolved": "https://cdn.royaleapi.com/static/img/cards/skeletons-ev1.png?v=1fbfe1a98e010442"
  },
  {
    "name": "アイススピリット",
    "english": "Ice Spirit",
    "slug": "ice-spirit",
    "id": 26000030,
    "yomi": "アイススピリット アイスピ アイス",
    "cost": 1,
    "type": "troop",
    "role": "凍結・サイクル",
    "img": "https://cdn.royaleapi.com/static/img/cards/ice-spirit.png?v=98a95155d1d2d24b",
    "evolved": true,
    "imgEvolved": "https://cdn.royaleapi.com/static/img/cards/ice-spirit-ev1.png?v=e29e486838459099"
  },
  {
    "name": "ファイアスピリット",
    "english": "Fire Spirit",
    "slug": "fire-spirit",
    "id": 26000031,
    "yomi": "ファイアスピリット ファイスピ ファイア",
    "cost": 1,
    "type": "troop",
    "role": "小型処理・対空",
    "img": "https://cdn.royaleapi.com/static/img/cards/fire-spirit.png?v=821bc1fca2e64fbd"
  },
  {
    "name": "エレクトロスピリット",
    "english": "Electro Spirit",
    "slug": "electro-spirit",
    "id": 26000084,
    "yomi": "エレクトロスピリット エレスピ エレクトロ",
    "cost": 1,
    "type": "troop",
    "role": "チェーン感電・サイクル",
    "img": "https://cdn.royaleapi.com/static/img/cards/electro-spirit.png?v=827660eb9904a490"
  },
  {
    "name": "ヒールスピリット",
    "english": "Heal Spirit",
    "slug": "heal-spirit",
    "id": 28000016,
    "yomi": "ヒールスピリット ヒースピ ヒルスピ ヒール ヒスピ",
    "cost": 1,
    "type": "troop",
    "role": "回復サポート",
    "img": "https://cdn.royaleapi.com/static/img/cards/heal-spirit.png?v=7f963f0f2c876d83"
  },
  {
    "name": "ゴブリン",
    "english": "Goblins",
    "slug": "goblins",
    "id": 26000002,
    "yomi": "ゴブリン ゴブ",
    "cost": 2,
    "type": "troop",
    "role": "小型高DPS",
    "img": "https://cdn.royaleapi.com/static/img/cards/goblins.png?v=00d9d8bf806763b6",
    "hero": true,
    "imgHero": "https://cdn.royaleapi.com/static/img/cards/goblins-hero.png?v=2ac5b1afb05be9ee"
  },
  {
    "name": "ボンバー",
    "english": "Bomber",
    "slug": "bomber",
    "id": 26000013,
    "yomi": "ボンバー ボンバ",
    "cost": 2,
    "type": "troop",
    "role": "範囲攻撃・防衛",
    "img": "https://cdn.royaleapi.com/static/img/cards/bomber.png?v=395d64da7c0a2c86",
    "evolved": true,
    "imgEvolved": "https://cdn.royaleapi.com/static/img/cards/bomber-ev1.png?v=fca63170b0013e50"
  },
  {
    "name": "槍ゴブリン",
    "english": "Spear Goblins",
    "slug": "spear-goblins",
    "id": 26000019,
    "yomi": "やりごぶりん やり ゴブ",
    "cost": 2,
    "type": "troop",
    "role": "対空・遠距離",
    "img": "https://cdn.royaleapi.com/static/img/cards/spear-goblins.png?v=43fad5130ced73c0"
  },
  {
    "name": "コウモリの群れ",
    "english": "Bats",
    "slug": "bats",
    "id": 26000049,
    "yomi": "コウモリの群れ コウモリ バット バツ",
    "cost": 2,
    "type": "troop",
    "role": "対空・サイクル",
    "img": "https://cdn.royaleapi.com/static/img/cards/bats.png?v=374760f39393d34f",
    "evolved": true,
    "imgEvolved": "https://cdn.royaleapi.com/static/img/cards/bats-ev1.png?v=2e08879eb89ebb28"
  },
  {
    "name": "アイスゴーレム",
    "english": "Ice Golem",
    "slug": "ice-golem",
    "id": 26000038,
    "yomi": "アイスゴーレム アイゴレ アイスゴレ ヒーローアイゴレ",
    "cost": 2,
    "type": "troop",
    "role": "タンク・デス凍結",
    "img": "https://cdn.royaleapi.com/static/img/cards/ice-golem.png?v=5eda1644bf91d7a6",
    "hero": true,
    "imgHero": "https://cdn.royaleapi.com/static/img/cards/ice-golem-hero.png?v=09254d250af3880a"
  },
  {
    "name": "ウォールブレイカー",
    "english": "Wall Breakers",
    "slug": "wall-breakers",
    "id": 26000058,
    "yomi": "ウォールブレイカー ウォールブレ ウォルブレ WB ウォール",
    "cost": 2,
    "type": "troop",
    "role": "建物狙い・サイクル",
    "img": "https://cdn.royaleapi.com/static/img/cards/wall-breakers.png?v=cb63770e8a7a69ce",
    "evolved": true,
    "imgEvolved": "https://cdn.royaleapi.com/static/img/cards/wall-breakers-ev1.png?v=1084f1f46801b23e"
  },
  {
    "name": "バーサーカー",
    "english": "Berserker",
    "slug": "berserker",
    "id": 26000102,
    "yomi": "バーサーカー バーサカ バサ子",
    "cost": 2,
    "type": "troop",
    "role": "高速高DPS近接",
    "img": "https://cdn.royaleapi.com/static/img/cards/berserker.png?v=bf57527c688f0352",
    "hero": true,
    "imgHero": "https://cdn.royaleapi.com/static/img/cards/berserker-hero.png?v=3141d9884e894875"
  },
  {
    "name": "ザップ",
    "english": "Zap",
    "slug": "zap",
    "id": 28000008,
    "yomi": "ザップ",
    "cost": 2,
    "type": "spell",
    "role": "即時感電・リセット",
    "img": "https://cdn.royaleapi.com/static/img/cards/zap.png?v=25bb27fc616058c9",
    "evolved": true,
    "imgEvolved": "https://cdn.royaleapi.com/static/img/cards/zap-ev1.png?v=341d5075933f1e6a"
  },
  {
    "name": "巨大雪玉",
    "english": "Giant Snowball",
    "slug": "giant-snowball",
    "id": 28000017,
    "yomi": "きょだいゆきだま ゆきだま 雪玉",
    "cost": 2,
    "type": "spell",
    "role": "ノックバック・減速",
    "img": "https://cdn.royaleapi.com/static/img/cards/giant-snowball.png?v=d32f6a45a27e6ada",
    "evolved": true,
    "imgEvolved": "https://cdn.royaleapi.com/static/img/cards/giant-snowball-ev1.png?v=d38545389c72b4ea"
  },
  {
    "name": "ローリングバーバリアン",
    "english": "Barbarian Barrel",
    "slug": "barbarian-barrel",
    "id": 28000015,
    "yomi": "ローリングバーバリアン バーバレル ロリバーバ ロリババ",
    "cost": 2,
    "type": "spell",
    "role": "転がし＋バーバリアン",
    "img": "https://cdn.royaleapi.com/static/img/cards/barbarian-barrel.png?v=1d2229729ace480b",
    "hero": true,
    "imgHero": "https://cdn.royaleapi.com/static/img/cards/barbarian-barrel-hero.png?v=5ba224e5a8ec3bbf"
  },
  {
    "name": "ローリングウッド",
    "english": "The Log",
    "slug": "the-log",
    "id": 28000011,
    "yomi": "ローリングウッド ログ THE LOG ウッド 丸太",
    "cost": 2,
    "type": "spell",
    "role": "広範囲ローリング",
    "img": "https://cdn.royaleapi.com/static/img/cards/the-log.png?v=42e3239e8d387559"
  },
  {
    "name": "レイジ",
    "english": "Rage",
    "slug": "rage",
    "id": 28000002,
    "yomi": "レイジ",
    "cost": 2,
    "type": "spell",
    "role": "速度・火力アップ",
    "img": "https://cdn.royaleapi.com/static/img/cards/rage.png?v=bd5feb30ea767ea0"
  },
  {
    "name": "ステルスブッシュ",
    "english": "Suspicious Bush",
    "slug": "suspicious-bush",
    "id": 26000097,
    "yomi": "ステルスブッシュ ブッシュ 茂み あやしいしげみ しげみ",
    "cost": 2,
    "type": "troop",
    "role": "茂みに隠れて潜伏",
    "img": "https://cdn.royaleapi.com/static/img/cards/suspicious-bush.png?v=d4d7ddda49ba5e9d"
  },
  {
    "name": "ゴブリンの呪い",
    "english": "Goblin Curse",
    "slug": "goblin-curse",
    "id": 28000024,
    "yomi": "ごぶりんののろい のろい カース ゴブカース 呪い",
    "cost": 2,
    "type": "spell",
    "role": "範囲呪い・倒すとゴブ化",
    "img": "https://cdn.royaleapi.com/static/img/cards/goblin-curse.png?v=5361990692e614b3"
  },
  {
    "name": "ナイト",
    "english": "Knight",
    "slug": "knight",
    "id": 26000000,
    "yomi": "ナイト",
    "cost": 3,
    "type": "troop",
    "role": "タンク・防衛",
    "img": "https://cdn.royaleapi.com/static/img/cards/knight.png?v=45e6b3e027909b64",
    "evolved": true,
    "imgEvolved": "https://cdn.royaleapi.com/static/img/cards/knight-ev1.png?v=42fd8322ecaee60a",
    "hero": true,
    "imgHero": "https://cdn.royaleapi.com/static/img/cards/knight-hero.png?v=967a501d81668438"
  },
  {
    "name": "アーチャー",
    "english": "Archers",
    "slug": "archers",
    "id": 26000001,
    "yomi": "アーチャー アチャ",
    "cost": 3,
    "type": "troop",
    "role": "対空・遠距離",
    "img": "https://cdn.royaleapi.com/static/img/cards/archers.png?v=514f1a55ed9d8094",
    "evolved": true,
    "imgEvolved": "https://cdn.royaleapi.com/static/img/cards/archers-ev1.png?v=c50b73193f54bd56"
  },
  {
    "name": "ガーゴイル",
    "english": "Minions",
    "slug": "minions",
    "id": 26000005,
    "yomi": "ガーゴイル ミニオン ガゴ",
    "cost": 3,
    "type": "troop",
    "role": "対空・高DPS",
    "img": "https://cdn.royaleapi.com/static/img/cards/minions.png?v=73a18171fbbd7e72"
  },
  {
    "name": "ゴブリンギャング",
    "english": "Goblin Gang",
    "slug": "goblin-gang",
    "id": 26000041,
    "yomi": "ゴブリンギャング ゴブギャ ギャング",
    "cost": 3,
    "type": "troop",
    "role": "地上・対空mix",
    "img": "https://cdn.royaleapi.com/static/img/cards/goblin-gang.png?v=42123f8029cb4b44"
  },
  {
    "name": "スケルトンバレル",
    "english": "Skeleton Barrel",
    "slug": "skeleton-barrel",
    "id": 26000056,
    "yomi": "スケルトンバレル スケバレ バレル スケブ",
    "cost": 3,
    "type": "troop",
    "role": "空中突撃・デス処理",
    "img": "https://cdn.royaleapi.com/static/img/cards/skeleton-barrel.png?v=2e180f0c54ab26c2",
    "evolved": true,
    "imgEvolved": "https://cdn.royaleapi.com/static/img/cards/skeleton-barrel-ev1.png?v=fd31aa047afa8302"
  },
  {
    "name": "ロケット砲士",
    "english": "Firecracker",
    "slug": "firecracker",
    "id": 26000064,
    "yomi": "ロケット砲士 ロケホウ ロケコ ファイクラ ファイアクラッカー ロケ子 ロケ 砲士",
    "cost": 3,
    "type": "troop",
    "role": "遠距離・小型処理",
    "img": "https://cdn.royaleapi.com/static/img/cards/firecracker.png?v=f27c2910aa12535d",
    "evolved": true,
    "imgEvolved": "https://cdn.royaleapi.com/static/img/cards/firecracker-ev1.png?v=817b1115dbb6f110"
  },
  {
    "name": "メガガーゴイル",
    "english": "Mega Minion",
    "slug": "mega-minion",
    "id": 26000039,
    "yomi": "メガガーゴイル メガゴ メガガゴ メガミニオン メガミニ ヒーローメガゴ",
    "cost": 3,
    "type": "troop",
    "role": "対空高火力",
    "img": "https://cdn.royaleapi.com/static/img/cards/mega-minion.png?v=37d61d8b65a104f3",
    "hero": true,
    "imgHero": "https://cdn.royaleapi.com/static/img/cards/mega-minion-hero.png?v=32a75f26ec78b326"
  },
  {
    "name": "吹き矢ゴブリン",
    "english": "Dart Goblin",
    "slug": "dart-goblin",
    "id": 26000040,
    "yomi": "ふきやごぶりん ふきや ダートゴブ ダーゴブ 吹き矢",
    "cost": 3,
    "type": "troop",
    "role": "超長射程・速射",
    "img": "https://cdn.royaleapi.com/static/img/cards/dart-goblin.png?v=add800376cd46119",
    "evolved": true,
    "imgEvolved": "https://cdn.royaleapi.com/static/img/cards/dart-goblin-ev1.png?v=ee335038104b383b"
  },
  {
    "name": "エリクサーゴーレム",
    "english": "Elixir Golem",
    "slug": "elixir-golem",
    "id": 26000067,
    "yomi": "エリクサーゴーレム エリゴレ",
    "cost": 3,
    "type": "troop",
    "role": "タンク・敵にエリ付与",
    "img": "https://cdn.royaleapi.com/static/img/cards/elixir-golem.png?v=bfd63510b89b8c65"
  },
  {
    "name": "アイスウィザード",
    "english": "Ice Wizard",
    "slug": "ice-wizard",
    "id": 26000023,
    "yomi": "アイスウィザード アイウィザ アイスウィズ アイウィズ",
    "cost": 3,
    "type": "troop",
    "role": "全体減速",
    "img": "https://cdn.royaleapi.com/static/img/cards/ice-wizard.png?v=93ef36e0e38cf303",
    "hero": true,
    "imgHero": "https://cdn.royaleapi.com/static/img/cards/ice-wizard-hero.png?v=0d87b0cdf56b6d9d"
  },
  {
    "name": "プリンセス",
    "english": "Princess",
    "slug": "princess",
    "id": 26000026,
    "yomi": "ぷりんせす プリセス プリン",
    "cost": 3,
    "type": "troop",
    "role": "超長射程・範囲",
    "img": "https://cdn.royaleapi.com/static/img/cards/princess.png?v=7cafdaff65b260cb",
    "evolved": true,
    "imgEvolved": "https://cdn.royaleapi.com/static/img/cards/princess-ev1.png?v=60ace6752ff85754"
  },
  {
    "name": "ディガー",
    "english": "Miner",
    "slug": "miner",
    "id": 26000032,
    "yomi": "ディガー マイナー ディガ",
    "cost": 3,
    "type": "troop",
    "role": "建物狙い奇襲",
    "img": "https://cdn.royaleapi.com/static/img/cards/miner.png?v=89abd0c605aab2b1"
  },
  {
    "name": "スケルトン部隊",
    "english": "Skeleton Army",
    "slug": "skeleton-army",
    "id": 26000012,
    "yomi": "スケルトン部隊 スケブ スケ部 スケアミ スケルトンアーミー",
    "cost": 3,
    "type": "troop",
    "role": "防衛・大量展開",
    "img": "https://cdn.royaleapi.com/static/img/cards/skeleton-army.png?v=342bdfb40b60566c",
    "evolved": true,
    "imgEvolved": "https://cdn.royaleapi.com/static/img/cards/skeleton-army-ev1.png?v=d829c3d39f54c1aa"
  },
  {
    "name": "盾の戦士",
    "english": "Guards",
    "slug": "guards",
    "id": 26000025,
    "yomi": "たてのせんし たて ガーズ",
    "cost": 3,
    "type": "troop",
    "role": "盾持ち防衛",
    "img": "https://cdn.royaleapi.com/static/img/cards/guards.png?v=c05066dba79f4dfa"
  },
  {
    "name": "アサシン ユーノ",
    "english": "Bandit",
    "slug": "bandit",
    "id": 26000046,
    "yomi": "アサシンユーノ ユーノ バンディット ユノ",
    "cost": 3,
    "type": "troop",
    "role": "ダッシュ高火力",
    "img": "https://cdn.royaleapi.com/static/img/cards/bandit.png?v=7d18a97c79f1dcf7"
  },
  {
    "name": "漁師トリトン",
    "english": "Fisherman",
    "slug": "fisherman",
    "id": 26000061,
    "yomi": "りょうしとりとん トリトン フィッシャーマン フィッシャ トリト",
    "cost": 3,
    "type": "troop",
    "role": "引き寄せ・妨害",
    "img": "https://cdn.royaleapi.com/static/img/cards/fisherman.png?v=8b8f565f5ebf3329"
  },
  {
    "name": "ロイヤルゴースト",
    "english": "Royal Ghost",
    "slug": "royal-ghost",
    "id": 26000050,
    "yomi": "ロイヤルゴースト ロイゴ ゴースト",
    "cost": 3,
    "type": "troop",
    "role": "透明・奇襲",
    "img": "https://cdn.royaleapi.com/static/img/cards/royal-ghost.png?v=02b22b232842236a",
    "evolved": true,
    "imgEvolved": "https://cdn.royaleapi.com/static/img/cards/royal-ghost-ev1.png?v=1018bc5c3513c97b"
  },
  {
    "name": "矢の雨",
    "english": "Arrows",
    "slug": "arrows",
    "id": 28000001,
    "yomi": "やのあめ アロー 矢 矢雨",
    "cost": 3,
    "type": "spell",
    "role": "範囲・対空",
    "img": "https://cdn.royaleapi.com/static/img/cards/arrows.png?v=5c0f34ee8f4b1399"
  },
  {
    "name": "トルネード",
    "english": "Tornado",
    "slug": "tornado",
    "id": 28000012,
    "yomi": "トルネード トルネ トル",
    "cost": 3,
    "type": "spell",
    "role": "引き寄せ・集中",
    "img": "https://cdn.royaleapi.com/static/img/cards/tornado.png?v=85625cdaea5c4373"
  },
  {
    "name": "アースクエイク",
    "english": "Earthquake",
    "slug": "earthquake",
    "id": 28000014,
    "yomi": "アースクエイク 地震 じしん クエイク",
    "cost": 3,
    "type": "spell",
    "role": "建物特効ダメージ",
    "img": "https://cdn.royaleapi.com/static/img/cards/earthquake.png?v=cfbddfbb2de7ad17"
  },
  {
    "name": "ロイヤルデリバリー",
    "english": "Royal Delivery",
    "slug": "royal-delivery",
    "id": 28000018,
    "yomi": "ろいやるでりばりー デリバリー",
    "cost": 3,
    "type": "spell",
    "role": "範囲＋兵士展開",
    "img": "https://cdn.royaleapi.com/static/img/cards/royal-delivery.png?v=68429aed5f6d88e9"
  },
  {
    "name": "ゴブリンバレル",
    "english": "Goblin Barrel",
    "slug": "goblin-barrel",
    "id": 28000004,
    "yomi": "ゴブリンバレル ゴブバレ バレル",
    "cost": 3,
    "type": "spell",
    "role": "奇襲ゴブリン3体",
    "img": "https://cdn.royaleapi.com/static/img/cards/goblin-barrel.png?v=c5ebf97e9a0e207b",
    "evolved": true,
    "imgEvolved": "https://cdn.royaleapi.com/static/img/cards/goblin-barrel-ev1.png?v=b2718021d573be92"
  },
  {
    "name": "クローン",
    "english": "Clone",
    "slug": "clone",
    "id": 28000013,
    "yomi": "クローン",
    "cost": 3,
    "type": "spell",
    "role": "ユニット複製",
    "img": "https://cdn.royaleapi.com/static/img/cards/clone.png?v=55477be87ef8578e"
  },
  {
    "name": "ヴァイン",
    "english": "Vines",
    "slug": "vines",
    "id": 28000026,
    "yomi": "ヴァイン バイン ツタ つた",
    "cost": 3,
    "type": "spell",
    "role": "高HP3体を拘束・空→地",
    "img": "https://cdn.royaleapi.com/static/img/cards/vines.png?v=2665775d37cd9ffb"
  },
  {
    "name": "ボイド",
    "english": "Void",
    "slug": "void",
    "id": 28000023,
    "yomi": "ボイド ぼいど",
    "cost": 5,
    "type": "spell",
    "role": "少数ほど高ダメージ",
    "img": "https://cdn.royaleapi.com/static/img/cards/void.png?v=86237a2d9812dad7"
  },
  {
    "name": "ミラー",
    "english": "Mirror",
    "slug": "mirror",
    "id": 28000006,
    "yomi": "ミラー みらー",
    "cost": 1,
    "type": "spell",
    "role": "直前カードを+1コスで複製",
    "img": "https://cdn.royaleapi.com/static/img/cards/mirror.png?v=7dbfca92439acf7e"
  },
  {
    "name": "大砲",
    "english": "Cannon",
    "slug": "cannon",
    "id": 27000000,
    "yomi": "おおづつ たいほう 大砲 キャノン",
    "cost": 3,
    "type": "building",
    "role": "単体遠距離防衛",
    "img": "https://cdn.royaleapi.com/static/img/cards/cannon.png?v=5d0dd593a29808b4",
    "evolved": true,
    "imgEvolved": "https://cdn.royaleapi.com/static/img/cards/cannon-ev1.png?v=d2c16fab62073e96"
  },
  {
    "name": "墓石",
    "english": "Tombstone",
    "slug": "tombstone",
    "id": 27000009,
    "yomi": "はかいし ぼせき はか いし トゥームストーン",
    "cost": 3,
    "type": "building",
    "role": "スケルトン生成",
    "img": "https://cdn.royaleapi.com/static/img/cards/tombstone.png?v=d01a136563b36873",
    "hero": true,
    "imgHero": "https://cdn.royaleapi.com/static/img/cards/tombstone-hero.png?v=45f1da4dcfd37873"
  },
  {
    "name": "バルキリー",
    "english": "Valkyrie",
    "slug": "valkyrie",
    "id": 26000011,
    "yomi": "バルキリー バルキ バルキリ バルキー",
    "cost": 4,
    "type": "troop",
    "role": "範囲防衛・タンク",
    "img": "https://cdn.royaleapi.com/static/img/cards/valkyrie.png?v=98dc946e8ba81eba",
    "evolved": true,
    "imgEvolved": "https://cdn.royaleapi.com/static/img/cards/valkyrie-ev1.png?v=057339910f888547",
    "hero": true,
    "imgHero": "https://cdn.royaleapi.com/static/img/cards/valkyrie-hero.png?v=51a07489e348a8bd"
  },
  {
    "name": "マスケット銃士",
    "english": "Musketeer",
    "slug": "musketeer",
    "id": 26000014,
    "yomi": "マスケット銃士 マスケ ヒーローマスケ マスキ",
    "cost": 4,
    "type": "troop",
    "role": "遠距離高火力",
    "img": "https://cdn.royaleapi.com/static/img/cards/musketeer.png?v=44eae961b5b57ee1",
    "evolved": true,
    "imgEvolved": "https://cdn.royaleapi.com/static/img/cards/musketeer-ev1.png?v=1ab9b07fbe2fecd1",
    "hero": true,
    "imgHero": "https://cdn.royaleapi.com/static/img/cards/musketeer-hero.png?v=6547117d46ab1a1c"
  },
  {
    "name": "ミニペッカ",
    "english": "Mini P.E.K.K.A",
    "slug": "mini-pekka",
    "id": 26000018,
    "yomi": "ミニペッカ ミニペ ミニピ ヒーローミニペ",
    "cost": 4,
    "type": "troop",
    "role": "単体超高DPS",
    "img": "https://cdn.royaleapi.com/static/img/cards/mini-pekka.png?v=0abe15669df86561",
    "hero": true,
    "imgHero": "https://cdn.royaleapi.com/static/img/cards/mini-pekka-hero.png?v=3885a61f2b8086f2"
  },
  {
    "name": "ホグライダー",
    "english": "Hog Rider",
    "slug": "hog-rider",
    "id": 26000021,
    "yomi": "ホグライダー ホグ",
    "cost": 4,
    "type": "troop",
    "role": "建物狙い突撃",
    "img": "https://cdn.royaleapi.com/static/img/cards/hog-rider.png?v=f1d0d1a8f187607b"
  },
  {
    "name": "攻城バーバリアン",
    "english": "Battle Ram",
    "slug": "battle-ram",
    "id": 26000036,
    "yomi": "こうじょうばーばりあん 攻城 攻城バーバリアン バトルラム ラム",
    "cost": 4,
    "type": "troop",
    "role": "建物狙い＋バーバリアン",
    "img": "https://cdn.royaleapi.com/static/img/cards/battle-ram.png?v=da6f1b2876c3058a",
    "evolved": true,
    "imgEvolved": "https://cdn.royaleapi.com/static/img/cards/battle-ram-ev1.png?v=05b6ef8bf754db36"
  },
  {
    "name": "スケルトンドラゴン",
    "english": "Skeleton Dragons",
    "slug": "skeleton-dragons",
    "id": 26000080,
    "yomi": "スケルトンドラゴン スケドラ",
    "cost": 4,
    "type": "troop",
    "role": "対空範囲",
    "img": "https://cdn.royaleapi.com/static/img/cards/skeleton-dragons.png?v=9c93acc6d8d7998b"
  },
  {
    "name": "ザッピー",
    "english": "Zappies",
    "slug": "zappies",
    "id": 26000052,
    "yomi": "ザッピー ザピ",
    "cost": 4,
    "type": "troop",
    "role": "感電・防衛",
    "img": "https://cdn.royaleapi.com/static/img/cards/zappies.png?v=9238d19b4905e1b4"
  },
  {
    "name": "ホバリング砲",
    "english": "Flying Machine",
    "slug": "flying-machine",
    "id": 26000057,
    "yomi": "ホバリング砲 ホバリング フライングマシン フラマシ ホバ マシン",
    "cost": 4,
    "type": "troop",
    "role": "対空・超長射程",
    "img": "https://cdn.royaleapi.com/static/img/cards/flying-machine.png?v=c8cadd07bf4be208"
  },
  {
    "name": "バトルヒーラー",
    "english": "Battle Healer",
    "slug": "battle-healer",
    "id": 26000068,
    "yomi": "バトルヒーラー ヒーラー バトヒ",
    "cost": 4,
    "type": "troop",
    "role": "HP回復タンク",
    "img": "https://cdn.royaleapi.com/static/img/cards/battle-healer.png?v=72b4666a52163eca"
  },
  {
    "name": "ダイナマイトゴブリン",
    "english": "Goblin Demolisher",
    "slug": "goblin-demolisher",
    "id": 26000095,
    "yomi": "ダイナマイトゴブリン ゴブデモ デモリッシャー",
    "cost": 4,
    "type": "troop",
    "role": "建物狙い・デス爆発",
    "img": "https://cdn.royaleapi.com/static/img/cards/goblin-demolisher.png?v=ede7285c0f9b9c43"
  },
  {
    "name": "ダークプリンス",
    "english": "Dark Prince",
    "slug": "dark-prince",
    "id": 26000027,
    "yomi": "ダークプリンス ダクプリ DP",
    "cost": 4,
    "type": "troop",
    "role": "盾＋範囲チャージ",
    "img": "https://cdn.royaleapi.com/static/img/cards/dark-prince.png?v=6b9234e605a03c16",
    "hero": true,
    "imgHero": "https://cdn.royaleapi.com/static/img/cards/dark-prince-hero.png?v=6c62b9865dec1912"
  },
  {
    "name": "ハンター",
    "english": "Hunter",
    "slug": "hunter",
    "id": 26000044,
    "yomi": "ハンター",
    "cost": 4,
    "type": "troop",
    "role": "近距離超高火力",
    "img": "https://cdn.royaleapi.com/static/img/cards/hunter.png?v=8954e6ab17e392f1",
    "evolved": true,
    "imgEvolved": "https://cdn.royaleapi.com/static/img/cards/hunter-ev1.png?v=bc67f36b1a9c5b71"
  },
  {
    "name": "ベビードラゴン",
    "english": "Baby Dragon",
    "slug": "baby-dragon",
    "id": 26000015,
    "yomi": "ベビードラゴン ベビドラ ベビー ベビ",
    "cost": 4,
    "type": "troop",
    "role": "対空範囲",
    "img": "https://cdn.royaleapi.com/static/img/cards/baby-dragon.png?v=2929dd7d006f6388",
    "evolved": true,
    "imgEvolved": "https://cdn.royaleapi.com/static/img/cards/baby-dragon-ev1.png?v=17c3c91e93fdf209"
  },
  {
    "name": "エレクトロウィザード",
    "english": "Electro Wizard",
    "slug": "electro-wizard",
    "id": 26000042,
    "yomi": "エレクトロウィザード エレウィザ エレウィズ EW エレキ",
    "cost": 4,
    "type": "troop",
    "role": "感電・リセット",
    "img": "https://cdn.royaleapi.com/static/img/cards/electro-wizard.png?v=a54e0f0bcb7ae39b"
  },
  {
    "name": "インフェルノドラゴン",
    "english": "Inferno Dragon",
    "slug": "inferno-dragon",
    "id": 26000037,
    "yomi": "インフェルノドラゴン インドラ インフェ",
    "cost": 4,
    "type": "troop",
    "role": "単体集中加熱",
    "img": "https://cdn.royaleapi.com/static/img/cards/inferno-dragon.png?v=ee2fcc081cd0706b",
    "evolved": true,
    "imgEvolved": "https://cdn.royaleapi.com/static/img/cards/inferno-dragon-ev1.png?v=dfe1e87766ba3c55"
  },
  {
    "name": "ランバージャック",
    "english": "Lumberjack",
    "slug": "lumberjack",
    "id": 26000035,
    "yomi": "ランバージャック ランバー ランバジャ",
    "cost": 4,
    "type": "troop",
    "role": "高速＋デスレイジ",
    "img": "https://cdn.royaleapi.com/static/img/cards/lumberjack.png?v=4f6f24e7b57884c8",
    "evolved": true,
    "imgEvolved": "https://cdn.royaleapi.com/static/img/cards/lumberjack-ev1.png?v=cb8d9d727dd70371"
  },
  {
    "name": "マジックアーチャー",
    "english": "Magic Archer",
    "slug": "magic-archer",
    "id": 26000062,
    "yomi": "マジックアーチャー マジアチャ MA マジア マジアチ ヒーローマジア",
    "cost": 4,
    "type": "troop",
    "role": "超射程貫通",
    "img": "https://cdn.royaleapi.com/static/img/cards/magic-archer.png?v=3bfca4e849635c20",
    "hero": true,
    "imgHero": "https://cdn.royaleapi.com/static/img/cards/magic-archer-hero.png?v=be2d198201042379"
  },
  {
    "name": "マザーネクロマンサー",
    "english": "Mother Witch",
    "slug": "mother-witch",
    "id": 26000083,
    "yomi": "マザーネクロマンサー マザネク マザー マザネ",
    "cost": 4,
    "type": "troop",
    "role": "呪い→ホグ変換",
    "img": "https://cdn.royaleapi.com/static/img/cards/mother-witch.png?v=4358533559228e83"
  },
  {
    "name": "ダークネクロ",
    "english": "Night Witch",
    "slug": "night-witch",
    "id": 26000048,
    "yomi": "ダークネクロ ダクネ ナイトウィッチ ナイウィチ ダネ",
    "cost": 4,
    "type": "troop",
    "role": "コウモリ生成",
    "img": "https://cdn.royaleapi.com/static/img/cards/night-witch.png?v=11a25cdc0f9e7ba0"
  },
  {
    "name": "ゴールドナイト",
    "english": "Golden Knight",
    "slug": "golden-knight",
    "id": 26000074,
    "yomi": "ゴールドナイト ゴルナイ GK ゴルナ",
    "cost": 4,
    "type": "troop",
    "role": "チャンピオン",
    "img": "https://cdn.royaleapi.com/static/img/cards/golden-knight.png?v=6055a75e85054a0c",
    "champion": true
  },
  {
    "name": "スケルトンキング",
    "english": "Skeleton King",
    "slug": "skeleton-king",
    "id": 26000069,
    "yomi": "スケルトンキング スケキン SK",
    "cost": 4,
    "type": "troop",
    "role": "チャンピオン",
    "img": "https://cdn.royaleapi.com/static/img/cards/skeleton-king.png?v=31997f851b4299ec",
    "champion": true
  },
  {
    "name": "マイティディガー",
    "english": "Mighty Miner",
    "slug": "mighty-miner",
    "id": 26000065,
    "yomi": "マイティディガー マイディガ MD マイティ",
    "cost": 4,
    "type": "troop",
    "role": "チャンピオン",
    "img": "https://cdn.royaleapi.com/static/img/cards/mighty-miner.png?v=efcfcaf5b7716cb5",
    "champion": true
  },
  {
    "name": "フェニックス",
    "english": "Phoenix",
    "slug": "phoenix",
    "id": 26000087,
    "yomi": "フェニックス フェニ",
    "cost": 4,
    "type": "troop",
    "role": "再生・対空",
    "img": "https://cdn.royaleapi.com/static/img/cards/phoenix.png?v=5a6973cc11048a11"
  },
  {
    "name": "鍛冶屋ジャイアント",
    "english": "Rune Giant",
    "slug": "rune-giant",
    "id": 26000101,
    "yomi": "かじやじゃいあんと かじジャイ ルーンジャイアント",
    "cost": 4,
    "type": "troop",
    "role": "味方2体にバフ付与",
    "img": "https://cdn.royaleapi.com/static/img/cards/rune-giant.png?v=593845a2b7a76125"
  },
  {
    "name": "ガーゴイルジャイアント",
    "english": "Minion Giant",
    "slug": "minion-giant",
    "id": 26000107,
    "yomi": "ガーゴイルジャイアント ガゴジャイ ミニオンジャイアント ガゴジャイアント ガーゴイルジャイ",
    "cost": 4,
    "type": "troop",
    "role": "空中建物狙い",
    "img": "https://cdn.royaleapi.com/static/img/cards/minion-giant.png?v=19e8d7fcfb798b8c"
  },
  {
    "name": "ファイアボール",
    "english": "Fireball",
    "slug": "fireball",
    "id": 28000000,
    "yomi": "ファイアボール ファイボ FB ファボ",
    "cost": 4,
    "type": "spell",
    "role": "中範囲高火力",
    "img": "https://cdn.royaleapi.com/static/img/cards/fireball.png?v=3678ef9bd9c900cc"
  },
  {
    "name": "フリーズ",
    "english": "Freeze",
    "slug": "freeze",
    "id": 28000005,
    "yomi": "フリーズ",
    "cost": 4,
    "type": "spell",
    "role": "全停止",
    "img": "https://cdn.royaleapi.com/static/img/cards/freeze.png?v=37794b0700edd5dc"
  },
  {
    "name": "ポイズン",
    "english": "Poison",
    "slug": "poison",
    "id": 28000009,
    "yomi": "ポイズン ポイズ",
    "cost": 4,
    "type": "spell",
    "role": "持続ダメージ",
    "img": "https://cdn.royaleapi.com/static/img/cards/poison.png?v=316dcdaf2f663478"
  },
  {
    "name": "ゴブリンの檻",
    "english": "Goblin Cage",
    "slug": "goblin-cage",
    "id": 27000012,
    "yomi": "ごぶりんのおり ゴブオリ おり ケージ 檻",
    "cost": 4,
    "type": "building",
    "role": "処理後ブロウラー生成",
    "img": "https://cdn.royaleapi.com/static/img/cards/goblin-cage.png?v=53623414bfc93845",
    "evolved": true,
    "imgEvolved": "https://cdn.royaleapi.com/static/img/cards/goblin-cage-ev1.png?v=a6dbbb609cfd0c79"
  },
  {
    "name": "ゴブリンドリル",
    "english": "Goblin Drill",
    "slug": "goblin-drill",
    "id": 27000013,
    "yomi": "ゴブリンドリル ゴブドリ ドリル",
    "cost": 4,
    "type": "building",
    "role": "地中攻撃",
    "img": "https://cdn.royaleapi.com/static/img/cards/goblin-drill.png?v=0323762c96673665",
    "evolved": true,
    "imgEvolved": "https://cdn.royaleapi.com/static/img/cards/goblin-drill-ev1.png?v=9b33a6b3733c85a1"
  },
  {
    "name": "ゴブリンの小屋",
    "english": "Goblin Hut",
    "slug": "goblin-hut",
    "id": 27000001,
    "yomi": "ごぶりんのこや ゴブゴヤ ゴブコヤ ゴブ小屋 ゴブこや ハット",
    "cost": 4,
    "type": "building",
    "role": "槍ゴブリン生成",
    "img": "https://cdn.royaleapi.com/static/img/cards/goblin-hut.png?v=bc8ca0e633573829"
  },
  {
    "name": "ボムタワー",
    "english": "Bomb Tower",
    "slug": "bomb-tower",
    "id": 27000004,
    "yomi": "ボムタワー ボムタワ",
    "cost": 4,
    "type": "building",
    "role": "範囲防衛",
    "img": "https://cdn.royaleapi.com/static/img/cards/bomb-tower.png?v=df04f829cd2bdfdd"
  },
  {
    "name": "テスラ",
    "english": "Tesla",
    "slug": "tesla",
    "id": 27000006,
    "yomi": "テスラ",
    "cost": 4,
    "type": "building",
    "role": "感電防衛",
    "img": "https://cdn.royaleapi.com/static/img/cards/tesla.png?v=b2f6309f2f661552",
    "evolved": true,
    "imgEvolved": "https://cdn.royaleapi.com/static/img/cards/tesla-ev1.png?v=e8d47cc1519cc510"
  },
  {
    "name": "迫撃砲",
    "english": "Mortar",
    "slug": "mortar",
    "id": 27000002,
    "yomi": "はくげきほう 迫撃 モーター モルタル",
    "cost": 4,
    "type": "building",
    "role": "超長射程建物狙い",
    "img": "https://cdn.royaleapi.com/static/img/cards/mortar.png?v=c2e2485c254a2ea7",
    "evolved": true,
    "imgEvolved": "https://cdn.royaleapi.com/static/img/cards/mortar-ev1.png?v=623c1adf0649765b"
  },
  {
    "name": "オーブン",
    "english": "Furnace",
    "slug": "furnace",
    "id": 27000010,
    "yomi": "オーブン かまど 炉",
    "cost": 4,
    "type": "building",
    "role": "ファイアスピリット生成",
    "img": "https://cdn.royaleapi.com/static/img/cards/furnace.png?v=b42075909e6b92f2",
    "evolved": true,
    "imgEvolved": "https://cdn.royaleapi.com/static/img/cards/furnace-ev1.png?v=fbf96eb3a834cb66"
  },
  {
    "name": "バーバリアン",
    "english": "Barbarians",
    "slug": "barbarians",
    "id": 26000008,
    "yomi": "バーバリアン ババ バーバリアン",
    "cost": 5,
    "type": "troop",
    "role": "高体力集団",
    "img": "https://cdn.royaleapi.com/static/img/cards/barbarians.png?v=c7c148be041721cd",
    "evolved": true,
    "imgEvolved": "https://cdn.royaleapi.com/static/img/cards/barbarians-ev1.png?v=9e1399efc66de5be"
  },
  {
    "name": "ガーゴイルの群れ",
    "english": "Minion Horde",
    "slug": "minion-horde",
    "id": 26000022,
    "yomi": "ガーゴイルの群れ ガゴムレ ガゴ群れ ミニオンホード ガゴ群",
    "cost": 5,
    "type": "troop",
    "role": "大量対空",
    "img": "https://cdn.royaleapi.com/static/img/cards/minion-horde.png?v=bb18b48ec8ffbfbe",
    "evolved": true,
    "imgEvolved": "https://cdn.royaleapi.com/static/img/cards/minion-horde-ev1.png?v=a8e65e54a0c0d0cb"
  },
  {
    "name": "ジャイアント",
    "english": "Giant",
    "slug": "giant",
    "id": 26000003,
    "yomi": "ジャイアント ジャイ ヒーロージャイ",
    "cost": 5,
    "type": "troop",
    "role": "建物狙いタンク",
    "img": "https://cdn.royaleapi.com/static/img/cards/giant.png?v=71685f53039eef1f",
    "hero": true,
    "imgHero": "https://cdn.royaleapi.com/static/img/cards/giant-hero.png?v=ef234c8a27810326"
  },
  {
    "name": "ウィザード",
    "english": "Wizard",
    "slug": "wizard",
    "id": 26000017,
    "yomi": "ウィザード ウィズ ヒーローウィズ",
    "cost": 5,
    "type": "troop",
    "role": "範囲スプラッシュ",
    "img": "https://cdn.royaleapi.com/static/img/cards/wizard.png?v=5b73620319ca1ce8",
    "evolved": true,
    "imgEvolved": "https://cdn.royaleapi.com/static/img/cards/wizard-ev1.png?v=3e004e3b27571695",
    "hero": true,
    "imgHero": "https://cdn.royaleapi.com/static/img/cards/wizard-hero.png?v=e37f78fcdd8f8dcc"
  },
  {
    "name": "エアバルーン",
    "english": "Balloon",
    "slug": "balloon",
    "id": 26000006,
    "yomi": "エアバルーン バルーン ヒーローバルーン バルン ヒーローバルン",
    "cost": 5,
    "type": "troop",
    "role": "建物狙い爆撃",
    "img": "https://cdn.royaleapi.com/static/img/cards/balloon.png?v=9a8a8a3e040bbb95",
    "hero": true,
    "imgHero": "https://cdn.royaleapi.com/static/img/cards/balloon-hero.png?v=f2795c4960d6e111"
  },
  {
    "name": "ネクロマンサー",
    "english": "Witch",
    "slug": "witch",
    "id": 26000007,
    "yomi": "ネクロマンサー ネクロ ウィッチ",
    "cost": 5,
    "type": "troop",
    "role": "スケルトン生成＋範囲",
    "img": "https://cdn.royaleapi.com/static/img/cards/witch.png?v=4fec852bcfed5665",
    "evolved": true,
    "imgEvolved": "https://cdn.royaleapi.com/static/img/cards/witch-ev1.png?v=d76a27f65085748a"
  },
  {
    "name": "ボウラー",
    "english": "Bowler",
    "slug": "bowler",
    "id": 26000034,
    "yomi": "ボウラー ボラ",
    "cost": 5,
    "type": "troop",
    "role": "貫通プッシュ",
    "img": "https://cdn.royaleapi.com/static/img/cards/bowler.png?v=efc34c2eca05f789",
    "hero": true,
    "imgHero": "https://cdn.royaleapi.com/static/img/cards/bowler-hero.png?v=b3d21573e97ee08e"
  },
  {
    "name": "執行人ファルチェ",
    "english": "Executioner",
    "slug": "executioner",
    "id": 26000045,
    "yomi": "しっこうにんふぁるちぇ ファルチェ エクスキュ エグゼ ファルチ ファル",
    "cost": 5,
    "type": "troop",
    "role": "貫通往復斧",
    "img": "https://cdn.royaleapi.com/static/img/cards/executioner.png?v=51121ae721fd7be4",
    "evolved": true,
    "imgEvolved": "https://cdn.royaleapi.com/static/img/cards/executioner-ev1.png?v=b6f5144f57f9dde6"
  },
  {
    "name": "60式ムート",
    "english": "Cannon Cart",
    "slug": "cannon-cart",
    "id": 26000054,
    "yomi": "60式ムート ムート キャノンカート",
    "cost": 5,
    "type": "troop",
    "role": "遠距離＋盾",
    "img": "https://cdn.royaleapi.com/static/img/cards/cannon-cart.png?v=380235930791c8cd"
  },
  {
    "name": "ロイヤルホグ",
    "english": "Royal Hogs",
    "slug": "royal-hogs",
    "id": 26000059,
    "yomi": "ロイヤルホグ ロイホグ",
    "cost": 5,
    "type": "troop",
    "role": "建物狙い4体",
    "img": "https://cdn.royaleapi.com/static/img/cards/royal-hogs.png?v=8b901e6e4118c4dd",
    "evolved": true,
    "imgEvolved": "https://cdn.royaleapi.com/static/img/cards/royal-hogs-ev1.png?v=9e5e628d2d19da51"
  },
  {
    "name": "アウトロー",
    "english": "Rascals",
    "slug": "rascals",
    "id": 26000053,
    "yomi": "アウトロー ラスカルズ",
    "cost": 5,
    "type": "troop",
    "role": "地空混合群",
    "img": "https://cdn.royaleapi.com/static/img/cards/rascals.png?v=cdf259ac78a61294"
  },
  {
    "name": "ライトニングドラゴン",
    "english": "Electro Dragon",
    "slug": "electro-dragon",
    "id": 26000063,
    "yomi": "ライトニングドラゴン ライドラ エレドラ 電気ドラゴン",
    "cost": 5,
    "type": "troop",
    "role": "チェーン感電",
    "img": "https://cdn.royaleapi.com/static/img/cards/electro-dragon.png?v=f9d2cc5854df4913",
    "evolved": true,
    "imgEvolved": "https://cdn.royaleapi.com/static/img/cards/electro-dragon-ev1.png?v=f5939dd0387a1c7c"
  },
  {
    "name": "プリンス",
    "english": "Prince",
    "slug": "prince",
    "id": 26000016,
    "yomi": "プリンス プリン",
    "cost": 5,
    "type": "troop",
    "role": "チャージ高火力",
    "img": "https://cdn.royaleapi.com/static/img/cards/prince.png?v=e5161d9b251e16c2"
  },
  {
    "name": "ラムライダー",
    "english": "Ram Rider",
    "slug": "ram-rider",
    "id": 26000051,
    "yomi": "ラムライダー ラム",
    "cost": 5,
    "type": "troop",
    "role": "建物狙い＋スネア",
    "img": "https://cdn.royaleapi.com/static/img/cards/ram-rider.png?v=fd6b7509feca3d63"
  },
  {
    "name": "リトルプリンス",
    "english": "Little Prince",
    "slug": "little-prince",
    "id": 26000093,
    "yomi": "リトルプリンス リトプリ LP",
    "cost": 3,
    "type": "troop",
    "role": "チャンピオン・盾持ち",
    "img": "https://cdn.royaleapi.com/static/img/cards/little-prince.png?v=cb98a98b67c13a4c",
    "champion": true
  },
  {
    "name": "モンク",
    "english": "Monk",
    "slug": "monk",
    "id": 26000077,
    "yomi": "モンク もんく",
    "cost": 5,
    "type": "troop",
    "role": "チャンピオン・攻防一体",
    "img": "https://cdn.royaleapi.com/static/img/cards/monk.png?v=53b61177014b2a80",
    "champion": true
  },
  {
    "name": "ゴブリンシュタイン",
    "english": "Goblinstein",
    "slug": "goblinstein",
    "id": 26000099,
    "yomi": "ゴブリンシュタイン ゴブリンスタイン ゴブシュタ シュタイン",
    "cost": 5,
    "type": "troop",
    "role": "チャンピオン・博士＋モンスター",
    "img": "https://cdn.royaleapi.com/static/img/cards/goblinstein.png?v=658cd662208a2e96",
    "champion": true
  },
  {
    "name": "ボスアサシン",
    "english": "Boss Bandit",
    "slug": "boss-bandit",
    "id": 26000103,
    "yomi": "ボスアサシン ボスバンディット ボスバン ボス",
    "cost": 6,
    "type": "troop",
    "role": "チャンピオン",
    "img": "https://cdn.royaleapi.com/static/img/cards/boss-bandit.png?v=4a0ac64bdc0d66a0",
    "champion": true
  },
  {
    "name": "アーチャークイーン",
    "english": "Archer Queen",
    "slug": "archer-queen",
    "id": 26000072,
    "yomi": "アーチャークイーン AQ アチャクイ クイーン",
    "cost": 5,
    "type": "troop",
    "role": "チャンピオン・高火力",
    "img": "https://cdn.royaleapi.com/static/img/cards/archer-queen.png?v=f66bfb78e3c0551e",
    "champion": true
  },
  {
    "name": "ゴブリンマシン",
    "english": "Goblin Machine",
    "slug": "goblin-machine",
    "id": 26000096,
    "yomi": "ゴブリンマシン ゴブマシン マシン",
    "cost": 5,
    "type": "troop",
    "role": "ロケット移動砲台",
    "img": "https://cdn.royaleapi.com/static/img/cards/goblin-machine.png?v=2b3d931ea377cf04"
  },
  {
    "name": "ローニン",
    "english": "Ronin",
    "slug": "ronin",
    "id": 26000106,
    "yomi": "ローニン ろーにん 浪人 スサノオ 浪人スサノオ Susanoo Susano Ronin スノ",
    "cost": 5,
    "type": "troop",
    "role": "受け流し近接反撃アタッカー",
    "img": "https://cdn.royaleapi.com/static/img/cards/ronin.png?v=114b39469d946df1"
  },
  {
    "name": "スケルトンラッシュ",
    "english": "Graveyard",
    "slug": "graveyard",
    "id": 28000010,
    "yomi": "スケルトンラッシュ スケラ グレイブヤード グレヤ 墓場",
    "cost": 5,
    "type": "spell",
    "role": "スケルトン大量召喚",
    "img": "https://cdn.royaleapi.com/static/img/cards/graveyard.png?v=ea37972ad1c8e92d"
  },
  {
    "name": "インフェルノタワー",
    "english": "Inferno Tower",
    "slug": "inferno-tower",
    "id": 27000003,
    "yomi": "インフェルノタワー インタワ IT インフェ",
    "cost": 5,
    "type": "building",
    "role": "単体集中加熱",
    "img": "https://cdn.royaleapi.com/static/img/cards/inferno-tower.png?v=5ad22d86b424ef1a"
  },
  {
    "name": "ロイヤルジャイアント",
    "english": "Royal Giant",
    "slug": "royal-giant",
    "id": 26000024,
    "yomi": "ロイヤルジャイアント ロイジャイ RG",
    "cost": 6,
    "type": "troop",
    "role": "建物狙い超射程",
    "img": "https://cdn.royaleapi.com/static/img/cards/royal-giant.png?v=6a55b73f6daaaa7a",
    "evolved": true,
    "imgEvolved": "https://cdn.royaleapi.com/static/img/cards/royal-giant-ev1.png?v=520a0d5ea9105713"
  },
  {
    "name": "エリートバーバリアン",
    "english": "Elite Barbarians",
    "slug": "elite-barbarians",
    "id": 26000043,
    "yomi": "エリートバーバリアン エリババ EB エリバ",
    "cost": 6,
    "type": "troop",
    "role": "高速高火力2体",
    "img": "https://cdn.royaleapi.com/static/img/cards/elite-barbarians.png?v=3697b3ebc34b46ed",
    "evolved": true,
    "imgEvolved": "https://cdn.royaleapi.com/static/img/cards/elite-barbarians-ev1.png?v=dadd6d2b01d7ad22"
  },
  {
    "name": "巨大スケルトン",
    "english": "Giant Skeleton",
    "slug": "giant-skeleton",
    "id": 26000020,
    "yomi": "きょだいすけるとん キョスケ ジャイスケ 巨大スケルトン 巨スケ",
    "cost": 6,
    "type": "troop",
    "role": "タンク＋デス爆弾",
    "img": "https://cdn.royaleapi.com/static/img/cards/giant-skeleton.png?v=e5f2acf2c25ad152"
  },
  {
    "name": "ゴブジャイアント",
    "english": "Goblin Giant",
    "slug": "goblin-giant",
    "id": 26000060,
    "yomi": "ゴブジャイアント ゴブジャイ",
    "cost": 6,
    "type": "troop",
    "role": "タンク＋槍ゴブリン",
    "img": "https://cdn.royaleapi.com/static/img/cards/goblin-giant.png?v=464f3a468a897af5",
    "evolved": true,
    "imgEvolved": "https://cdn.royaleapi.com/static/img/cards/goblin-giant-ev1.png?v=802cbbfc93ea37ee"
  },
  {
    "name": "スパーキー",
    "english": "Sparky",
    "slug": "sparky",
    "id": 26000033,
    "yomi": "スパーキー スパキ スパ",
    "cost": 6,
    "type": "troop",
    "role": "蓄電超高火力",
    "img": "https://cdn.royaleapi.com/static/img/cards/sparky.png?v=58ae30a4289ff024"
  },
  {
    "name": "スピリットエンプレス",
    "english": "Spirit Empress",
    "slug": "spirit-empress",
    "id": 28000025,
    "yomi": "スピリットエンプレス エンプレス せいれい",
    "cost": 6,
    "type": "troop",
    "role": "3コス陸/6コス空の二形態",
    "img": "https://cdn.royaleapi.com/static/img/cards/spirit-empress.png?v=698f4782c1cfda53"
  },
  {
    "name": "ロケット",
    "english": "Rocket",
    "slug": "rocket",
    "id": 28000003,
    "yomi": "ロケット ロケ",
    "cost": 6,
    "type": "spell",
    "role": "超高火力単発",
    "img": "https://cdn.royaleapi.com/static/img/cards/rocket.png?v=3729d4770b5a7bd6"
  },
  {
    "name": "ライトニング",
    "english": "Lightning",
    "slug": "lightning",
    "id": 28000007,
    "yomi": "ライトニング 雷 ライト",
    "cost": 6,
    "type": "spell",
    "role": "3体感電高火力",
    "img": "https://cdn.royaleapi.com/static/img/cards/lightning.png?v=e66b4dfc00a5ce2d"
  },
  {
    "name": "エリクサーポンプ",
    "english": "Elixir Collector",
    "slug": "elixir-collector",
    "id": 27000007,
    "yomi": "えりくさーぽんぷ ポンプ エリポン",
    "cost": 6,
    "type": "building",
    "role": "エリクサー生成",
    "img": "https://cdn.royaleapi.com/static/img/cards/elixir-collector.png?v=496627ae5acb4dd0"
  },
  {
    "name": "バーバリアンの小屋",
    "english": "Barbarian Hut",
    "slug": "barbarian-hut",
    "id": 27000005,
    "yomi": "ばーばりあんのこや ババこや バーバハット ババ小屋",
    "cost": 6,
    "type": "building",
    "role": "バーバリアン生成",
    "img": "https://cdn.royaleapi.com/static/img/cards/barbarian-hut.png?v=6bf3af642d99dcd7"
  },
  {
    "name": "巨大クロスボウ",
    "english": "X-Bow",
    "slug": "x-bow",
    "id": 27000008,
    "yomi": "きょだいくろすぼう Xボウ クロスボウ クロス",
    "cost": 6,
    "type": "building",
    "role": "超長射程建物狙い",
    "img": "https://cdn.royaleapi.com/static/img/cards/x-bow.png?v=caa509d1a28b9236"
  },
  {
    "name": "ペッカ",
    "english": "P.E.K.K.A",
    "slug": "pekka",
    "id": 26000004,
    "yomi": "ペッカ PEKKA",
    "cost": 7,
    "type": "troop",
    "role": "単体超高DPS",
    "img": "https://cdn.royaleapi.com/static/img/cards/pekka.png?v=b2e7d18ff977f495",
    "evolved": true,
    "imgEvolved": "https://cdn.royaleapi.com/static/img/cards/pekka-ev1.png?v=83dd058d41a24e36"
  },
  {
    "name": "ラヴァハウンド",
    "english": "Lava Hound",
    "slug": "lava-hound",
    "id": 26000029,
    "yomi": "ラヴァハウンド ラヴァ ラバ",
    "cost": 7,
    "type": "troop",
    "role": "空中タンク",
    "img": "https://cdn.royaleapi.com/static/img/cards/lava-hound.png?v=f0789d1aa3663b7a"
  },
  {
    "name": "エレクトロジャイアント",
    "english": "Electro Giant",
    "slug": "electro-giant",
    "id": 26000085,
    "yomi": "エレクトロジャイアント エレジャイ EG",
    "cost": 7,
    "type": "troop",
    "role": "感電反射タンク",
    "img": "https://cdn.royaleapi.com/static/img/cards/electro-giant.png?v=4c00a053b60229dd"
  },
  {
    "name": "メガナイト",
    "english": "Mega Knight",
    "slug": "mega-knight",
    "id": 26000055,
    "yomi": "メガナイト メガナイ MK メガナ",
    "cost": 7,
    "type": "troop",
    "role": "スポーン＋ジャンプ範囲",
    "img": "https://cdn.royaleapi.com/static/img/cards/mega-knight.png?v=37a5b9aa81fe8ba4",
    "evolved": true,
    "imgEvolved": "https://cdn.royaleapi.com/static/img/cards/mega-knight-ev1.png?v=c753041791e478fd"
  },
  {
    "name": "見習い親衛隊",
    "english": "Royal Recruits",
    "slug": "royal-recruits",
    "id": 26000047,
    "yomi": "みならいしんえいたい 親衛隊 ロイリク リクルート",
    "cost": 7,
    "type": "troop",
    "role": "壁役6体",
    "img": "https://cdn.royaleapi.com/static/img/cards/royal-recruits.png?v=53827d02a6ed48be",
    "evolved": true,
    "imgEvolved": "https://cdn.royaleapi.com/static/img/cards/royal-recruits-ev1.png?v=fc955c88649abc6a"
  },
  {
    "name": "ゴーレム",
    "english": "Golem",
    "slug": "golem",
    "id": 26000009,
    "yomi": "ゴーレム ゴレ",
    "cost": 8,
    "type": "troop",
    "role": "最大タンク",
    "img": "https://cdn.royaleapi.com/static/img/cards/golem.png?v=39cab32ac874e24a"
  },
  {
    "name": "三銃士",
    "english": "Three Musketeers",
    "slug": "three-musketeers",
    "id": 26000028,
    "yomi": "さんじゅうし 三銃士 スリーマスケット",
    "cost": 9,
    "type": "troop",
    "role": "超高火力3体",
    "img": "https://cdn.royaleapi.com/static/img/cards/three-musketeers.png?v=c5d0d89da5d384c1"
  }
];
const CARD_INFO = Object.fromEntries(CARDS.map(c => [c.name, {
  c: c.cost, i: c.img || '', iv: c.imgEvolved || '', ih: c.imgHero || '',
  e: !!c.evolved, h: !!c.hero, ch: !!c.champion
}]));
const CARD_YOMI = Object.fromEntries(CARDS.map(c => [c.name, c.yomi || '']));

/* ══════ カード検索の照合も「ここだけ」に書く（全ページ共通の正本） ══════
 * ★2026-08-11に確立。それまで builder.js と decks.js が別々に照合を書いていて、
 *   検索ボックスごとに拾える語が違っていた。検索ボックスを足すたびに実装を写す形は
 *   画像のときと同じ「1か所直しても全体に効かない」を生むのでやめる。
 *
 * 【鉄則】検索の絞り込みは必ず cardSearchMatch() / cardSearchFilter() を通す。
 *         c.yomi や CARD_YOMI を照合のために直接読んではいけない。
 *         違反は `node tools/check-card-images.js` が検出して落とす。
 *
 * 拾えるもの（すべて大小・ひらがな/カタカナ・全角半角・記号差を吸収）:
 *   - 正規名（"ホグライダー"）／表示名（"浪人スサノオ"）
 *   - 読み・略称（yomi。YouTube121本の実況字幕から採った130形を収録・2026-08-11）
 *   - 英語名＝画像スラッグ（"hog"／"Hog Rider"／"hogrider"）
 * 略称を足したいときは CARDS の yomi にスペース区切りで書き足すだけでよい。 */
// 半角カナ→全角カナ（濁点・半濁点を合成する）。"ﾎｸﾞ" で検索されても拾えるようにする。
var CR_HANKAKU = 'ｱｲｳｴｵｶｷｸｹｺｻｼｽｾｿﾀﾁﾂﾃﾄﾅﾆﾇﾈﾉﾊﾋﾌﾍﾎﾏﾐﾑﾒﾓﾔﾕﾖﾗﾘﾙﾚﾛﾜｦﾝｧｨｩｪｫｯｬｭｮｰ';
var CR_ZENKAKU = 'アイウエオカキクケコサシスセソタチツテトナニヌネノハヒフヘホマミムメモヤユヨラリルレロワヲンァィゥェォッャュョー';
function crHankakuToZen(s) {
  var out = '';
  for (var i = 0; i < s.length; i++) {
    var ch = s[i], j = CR_HANKAKU.indexOf(ch);
    var base = j >= 0 ? CR_ZENKAKU[j] : ch;
    var nx = s[i + 1];
    if (j >= 0 && (nx === 'ﾞ' || nx === 'ﾟ')) {
      var comp = base.normalize('NFC');
      var dak = (nx === 'ﾞ' ? '\u3099' : '\u309A');
      var merged = (comp + dak).normalize('NFC');
      if (merged.length === 1) { out += merged; i++; continue; }
    }
    out += base;
  }
  return out;
}
function crNormJa(s) {
  return crHankakuToZen(String(s == null ? '' : s))
    .toLowerCase()
    .replace(/[Ａ-Ｚａ-ｚ０-９]/g, c => String.fromCharCode(c.charCodeAt(0) - 0xFEE0)) // 全角英数→半角
    .replace(/[ァ-ヶ]/g, c => String.fromCharCode(c.charCodeAt(0) - 0x60))            // カタカナ→ひらがな
    .replace(/[・･\-\s.]/g, '');                       // 中黒・ハイフン・空白・ピリオドを無視
}
function crNormEn(s) {
  return String(s == null ? '' : s)
    .replace(/[Ａ-Ｚａ-ｚ０-９]/g, c => String.fromCharCode(c.charCodeAt(0) - 0xFEE0))
    .toLowerCase().replace(/[^a-z0-9]/g, '');
}
function cardSearchTerms(card) {
  const c = (typeof card === 'string') ? (CARDS.find(x => x.name === card) || null) : card;
  if (!c) return { ja: [], en: [] };
  const slug = ((c.img || '').match(/\/([a-z0-9-]+)\.png/i) || [])[1] || '';
  return {
    ja: [c.name, c.displayName, c.yomi].filter(Boolean).join(' ').split(/\s+/).filter(Boolean).map(crNormJa),
    en: [slug, c.name].filter(Boolean).map(crNormEn).filter(Boolean)
  };
}
function cardSearchMatch(card, query) {
  const q = String(query == null ? '' : query).trim();
  if (!q) return true;
  const t = cardSearchTerms(card);
  const qja = crNormJa(q);
  if (qja && t.ja.some(x => x.indexOf(qja) >= 0)) return true;
  const qen = crNormEn(q);
  return !!qen && t.en.some(x => x.indexOf(qen) >= 0);
}
// 完全一致で1枚に決めたいとき用（ゲームからのペースト取り込みなど）。
// 部分一致の cardSearchMatch と違い、正規化した語がぴったり一致したものだけを返す。
function cardResolveExact(word) {
  const q = crNormJa(word), qe = crNormEn(word);
  if (!q && !qe) return null;
  for (const c of CARDS) {
    const t = cardSearchTerms(c);
    if (q && t.ja.some(x => x === q)) return c.name;
    if (qe && t.en.some(x => x === qe)) return c.name;
  }
  return null;
}
// カード配列（省略時は全カード）を絞り込む。名前の配列を渡しても動く。
function cardSearchFilter(query, list) {
  const src = list || CARDS;
  return src.filter(x => cardSearchMatch(x, query));
}

/* ══════ カード画像の解決は「ここだけ」に書く（全ページ共通の正本） ══════
 * ★2026-08-11に確立したルール。
 *   それまで <img> を出す箇所が js/ 全体に22か所あり、4通りの独自ルールで
 *   画像を決めていた。そのため「1か所直しても全体に効かない」状態で、
 *   ランキングやカード検索が形態（進化/英雄）を無視して通常画像を出していた。
 *
 * 【鉄則】新しく <img> を書くときは必ず cardImageSrc() を通す。
 *         CARD_INFO の .i / .iv / .ih や CARDS の .img / .imgEvolved / .imgHero を
 *         描画側から直接読んではいけない。
 *         違反は `node tools/check-card-images.js` が検出して落とす（CIで毎回走る）。
 *
 * name : "ナイト" でも "ナイト⚡" / "ナイト👑" でも可（末尾の記号から形態を読む）
 * form : 'e'|'evolved'|'⚡' ／ 'h'|'hero'|'👑' ／ 'n'|'normal'／未指定
 *        指定が name の記号と食い違う場合は form を優先する。
 * ★存在しない形態を要求されたら通常画像へ落とす。バッジ（⚡/👑）も cardFormMark() が
 *   同じ判定を使うので、「⚡が付いているのに絵は通常」という食い違いが起きない。 */
function cardBaseName(name) { return String(name == null ? '' : name).replace(/[⚡👑]+$/, ''); }
function cardFormOf(name, form) {
  var f = form == null ? '' : String(form);
  if (!f) { var s = String(name || '').slice(cardBaseName(name).length); f = s; }
  if (f === 'e' || f === 'evo' || f === 'evolved' || f === '⚡') return 'e';
  if (f === 'h' || f === 'hero' || f === '👑') return 'h';
  return ['', 'n', 'norm', 'normal', 'champ', 'champion'].includes(f) ? 'n' : 'unknown';
}
function cardHasForm(name, form) {
  var info = CARD_INFO[cardBaseName(name)];
  if (!info) return false;
  var f = cardFormOf(name, form);
  return f === 'e' ? !!info.iv : f === 'h' ? !!info.ih : f === 'n';
}
function cardPlaceholderSrc(name) {
  var label = String(name || 'カード').replace(/[<>&"']/g, '');
  var svg = '<svg xmlns="http://www.w3.org/2000/svg" width="302" height="363"><rect x="8" y="8" width="286" height="347" rx="26" fill="#17283c" stroke="#80afd2" stroke-width="5"/><path d="M100 135h102v80H100zM100 193l30-30 26 25 18-14 28 27" fill="none" stroke="#80afd2" stroke-width="6"/><text x="151" y="255" text-anchor="middle" fill="#fff" font-size="16">' + label + '</text><text x="151" y="283" text-anchor="middle" fill="#c4d7e6" font-size="14">画像を確認中</text></svg>';
  return 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(svg);
}
function cardImageSrc(name, form) {
  var base = cardBaseName(name);
  var info = CARD_INFO[base];
  if (!info) return cardPlaceholderSrc(base);
  var f = cardFormOf(name, form);
  if (f === 'e') return info.iv || cardPlaceholderSrc(base + '・限界突破');
  if (f === 'h') return info.ih || cardPlaceholderSrc(base + '・ヒーロー');
  if (f !== 'n') return cardPlaceholderSrc(base);
  return info.i || '';
}
// 実際に表示される形態（存在しない形態を要求されたら 'n' に落ちる）
function cardShownForm(name, form) { return cardHasForm(name, form) ? cardFormOf(name, form) : 'n'; }
function cardFormMark(name, form) { var f = cardShownForm(name, form); return f === 'e' ? '⚡' : f === 'h' ? '👑' : ''; }
// <img> タグごと作る。alt と loading を書き忘れないための入口。
function cardImgTag(name, form, opt) {
  var src = cardImageSrc(name, form);
  if (!src) return '';
  var o = opt || {};
  return '<img' + (o.cls ? ' class="' + o.cls + '"' : '') + ' src="' + src + '" alt="' +
    String(o.alt != null ? o.alt : cardBaseName(name)).replace(/"/g, '&quot;') + '"' +
    (o.eager ? '' : ' loading="lazy"') + '>';
}

// Same-card, same-form fallback only. Never hide a failed image or substitute a normal form.
(function () {
  if (typeof document === 'undefined' || window.__crImgFallback) return;
  window.__crImgFallback = true;
  document.addEventListener('error', function (e) {
    var img = e && e.target;
    if (!img || img.tagName !== 'IMG') return;
    var src = img.currentSrc || img.src || '';
    if (!/cdn\.royaleapi\.com|raw\.githubusercontent\.com\/RoyaleAPI\/cr-api-assets/.test(src)) return;
    var match = src.match(/\/([a-z0-9-]+)\.png(\?.*)?$/i);
    if (!match) return;
    var step = +(img.getAttribute('data-imgfb') || 0);
    img.setAttribute('data-imgfb', String(step + 1));
    if (step === 0) {
      var host = /raw\.githubusercontent/.test(src) ? 'https://cdn.royaleapi.com/static/img/cards/' : 'https://raw.githubusercontent.com/RoyaleAPI/cr-api-assets/master/cards/';
      img.src = host + match[1] + '.png' + (match[2] || '');
      return;
    }
    var label = String(img.alt || match[1]).replace(/[<>&"']/g, '');
    img.title = label + '：画像を取得できませんでした';
    img.setAttribute('data-image-unavailable', 'true');
    img.src = cardPlaceholderSrc(label);
  }, true);
})();
